version: '3'

services:
  postgresql:
    image: postgres:10
    container_name: otus_hw_13
    environment:
      - POSTGRES_DB=otus_adverts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql
      - ./scripts:/docker-entrypoint-initdb.d
